# Generated by Django 3.2.12 on 2022-03-25 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DailySummaryPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pair', models.CharField(max_length=10)),
                ('timestamp', models.IntegerField()),
                ('mms_20', models.FloatField(blank=True, null=True)),
                ('mms_50', models.FloatField(blank=True, null=True)),
                ('mms_200', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'daily_summary_price',
            },
        ),
    ]
